### ISSUE TITLE
Create Account Request From & Update FINOS.org Alloy Page 

### ISSUE THREAD

**Issue by brooklynrob** [finos/legend#203]
One eve of go-live (i.e., open sourcing; https://github.com/finos/alloy/milestone/6) a new version of the finos.org/alloy page needs to be published.

The form should ask:
- Name (**)
- Company (**)
     - FINOS member? (include link to list of FINOS members)
- Email (Corporate Email Preferred) (**)
- Github handle (**; include link to github account create)
- Access Level Requested (note: If not specified/left blank, we should set up as read only)
     - I only want/need to view models (read only access)
     - I want to create and edit models (write access; note CLA coverage is required for write access)
- "I am covered under an existing FINOS CCLA/ICLA" (**; link to info about FINOS CLA policy)
     - Yes, CCLA (my employer's CLA)
     - Yes, ICLA (I have an individual CLA with FINOS)
     - No
     - Don't Know
- Reason for Account (Check All that Apply)
     - Existing FINOS modeling initiative
          - Extensions to the ISDA CDM FX Option model
          - Commodities Reference Data
          - Currency Reference Data
          - Other: (Text box)
    - Existing FINOS project
        - List: (One-line text field)
    - New Modeling Initiative of Project
        - Describe: (paragraph text box)
    - "Sandbox" Use (I want to try Alloy out and practice building models)

Ahead of the night of go-live the following should be drafted, built, tested, and staged.

## Tasks
- [x] Create an Account Request Form (to embed in the page) @maoo 
- [ ] Update URL to `www.finos.org/<newname>` (@maoo @grizzwolf)
     - [ ] Test that previous urls, www.finos.org/purealloy and www.finos.org/alloy still work (i.e., still point to the page now as the new URL (@maoo @grizzwolf)
- [ ] Update page copy to reflect current progress and status (@grizzwolf)
     - [ ] Supply copy (@aitana16 @brooklynrob) 

(**) ==> Mandatory
(This is a effectively a revision to the original issue to set up this page last year, tracked at https://github.com/finos/alloy/issues/18)

**Comment by maoo** [comment]
Attaching preview of the form....

![screencapture-share-hsforms-1NAmODelWQ1qiijdGHUKgpg1fux8-2020-08-19-12_16_36](https://user-images.githubusercontent.com/327285/90622769-e147ef80-e215-11ea-95a9-73236544f201.png)

@brooklynrob @aitana16 - please review and let me know. TY!

**Comment by brooklynrob** [comment]
@maoo @aitana16 Additional piece I neglected to add above -- the form should be configured to send the form results to alloy-inqui... (at)finos.org

**Comment by brooklynrob** [comment]
@maoo I reviewed the screenshot preview of the form above. Thanks for starting this. 

The "Reason for Account" should be checkboxes not radio buttons (See "Check All that Apply") -- i.e., requestors should be able to choose multiple reasons/purposes for the account.

**Comment by maoo** [comment]
TY @brooklynrob, that helps. I've used checkboxes and used alloy-inquiries(at)finos.org

**Comment by brooklynrob** [comment]
Awesome, thanks @maoo!

**Comment by maoo** [comment]
@brooklynrob @aitana16 @grizzwolf - can this be closed because either the work is done or it's tracked elsewhere? TY!

**Comment by aitana16** [comment]
hi @maoo the account request form is live at https://www.finos.org/alloy, however the finos.org alloy page still needs to be updated and will be published on the eve of open sourcing (i.e. end of september), so I don't think this issue can be closed yet.

**Comment by aitana16** [comment]
Done, thanks @grizzwolf
