### ISSUE TITLE
Examples of feature disparities - Legend vs Rosetta for CDM?

### ISSUE THREAD

**Issue by smsant** [finos/legend#719]
**Hi, has anyone used both Legend + Rosetta and faced problems with inconsistencies/feature disparities between the two DSLs? I am polling for prevalent issues to investigate.** 

This is part of a [potential research project](https://docs.google.com/document/d/1CdZe6YuE-9ilwkL6J11u4yqwJwb-PJCICVUrnEiubtk/edit?usp=sharing) on the compatibility of using two DSLs to work with the CDM.

# My current trajectory
Given I am new to FINOS, I'm very open to and actively seeking feedback!

## TODO
Assess feature disparity between Pure and Rosetta:

- [ ] 1. Explore "diff" approaches to compare transpiled Rosetta (from Pure) against the original Rosetta, and vice versa.
	- **_The purpose of this post is to gather input samples/test cases for this._** 
- [ ] 2. [Manually evaluate](https://docs.google.com/spreadsheets/d/1BnjLrR-CRKNJv75dZfddr_00AH_0SgrzBl1xcNBEDWk/edit?usp=sharing) modeling capabilities of each DSL (via documentation review and domain-agnostic modeling tests). Unclear if this is helpful.
- [ ] 3. Test [Morphir](https://morphir.finos.org/) as a target IR.

## What I know so far + additional questions

1. The Legend/Pure -> Rosetta pipeline seems fleshed out. 
	- I can transpile the Legend CDM back to Rosetta (using "New File Generation.."). This appears to solve #300 , as well as the code generator discussion in #311.
		- _How do members typically deploy the `rosettaTypes.txt` output? Is this out of scope of the "Pure to Rosetta translation" problem?_
		- _What else might I be missing? (e.g., problems people face using the generated Rosetta?)_
	
2. The Rosetta -> Legend/Pure pipeline looks less developed.
	- Per #650 (under "Other"), Rosetta CDM versions are not pushed regularly to Legend. The problem cited is "opaque expressions".
		- _What are some examples of these "opaque expressions"?_
		- _Besides opaque expressions, are there other known bottlenecks (technical or otherwise) for regularly pushing Rosetta versions to Legend?_
	- (Sidenote: I recently learned that the Legend CDM was updated last month to match the latest Rosetta CDM.)

3. ISDA review is required for all CDM changes (e.g., those made in Legend) pushed to the official Rosetta CDM. 
	-  From: #335
		- _Is this review stage beyond the scope of DSL compatibility?_
		- _Is this review done at a purely logical level? Or are technical inconsistencies ironed out between DSLs?_

4. I am looking into [Morphir](https://morphir.finos.org/) as a target IR and am just starting to explore how FpML fits into all this.

**Comment by beekemarie** [comment]
Hi @smsant - would recommend that you reach out to the FINOS Technical SteerCo to find out more. I think they engaged in a feature comparison analysis.

**Comment by smsant** [comment]
@beekemarie - sounds good, thanks for the guidance!

**Comment by finos-admin** [comment]
This issue is stale because it has been open for 30 days with no activity. Please remove stale label or add any comment to keep this open. Otherwise this will be closed in 5 days.

**Comment by finos-admin** [comment]
This issue was closed because it has been inactive for 35 days. Please re-open if this issue is still relevant.
